// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UssdDevelopmentCore.Database;

#nullable disable

namespace UssdDevelopmentCore.Migrations
{
    [DbContext(typeof(NasdacDatabase))]
    partial class NasdacDatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TransactionStatus", new[] { "pending", "successful", "failed" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "TransactionType", new[] { "deposit", "withdraw", "wallet_to_wallet", "wallet_to_mobile_money" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "VoucherStatus", new[] { "open", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UssdDevelopmentCore.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WalletPin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("wallet_pin");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.ToTable("Members", (string)null);
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.SmsMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sms_messages");

                    b.ToTable("SmsMessages", (string)null);
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.VoucherTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("VoucherStatus")
                        .HasColumnType("integer")
                        .HasColumnName("voucher_status");

                    b.Property<int>("WalletTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_voucher_transactions");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_voucher_transactions_member_id");

                    b.HasIndex("WalletTransactionId")
                        .HasDatabaseName("ix_voucher_transactions_wallet_transaction_id");

                    b.ToTable("VoucherTransactions", (string)null);
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ClosingBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("closing_balance");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<decimal>("OpeningBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("opening_balance");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("WalletTransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_transaction_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_wallets_member_id");

                    b.HasIndex("WalletTransactionId")
                        .HasDatabaseName("ix_wallets_wallet_transaction_id");

                    b.ToTable("Wallets", (string)null);
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("BilledAccount")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("billed_account");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExternalTxnId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_txn_id");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer")
                        .HasColumnName("member_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transaction_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_wallet_transactions");

                    b.HasIndex("MemberId")
                        .HasDatabaseName("ix_wallet_transactions_member_id");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.VoucherTransaction", b =>
                {
                    b.HasOne("UssdDevelopmentCore.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_transactions_members_member_id");

                    b.HasOne("UssdDevelopmentCore.Models.WalletTransaction", "WalletTransaction")
                        .WithMany()
                        .HasForeignKey("WalletTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_voucher_transactions_wallet_transactions_wallet_transaction_id");

                    b.Navigation("Member");

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.Wallet", b =>
                {
                    b.HasOne("UssdDevelopmentCore.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_members_member_id");

                    b.HasOne("UssdDevelopmentCore.Models.WalletTransaction", "WalletTransaction")
                        .WithMany()
                        .HasForeignKey("WalletTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_wallet_transactions_wallet_transaction_id");

                    b.Navigation("Member");

                    b.Navigation("WalletTransaction");
                });

            modelBuilder.Entity("UssdDevelopmentCore.Models.WalletTransaction", b =>
                {
                    b.HasOne("UssdDevelopmentCore.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallet_transactions_members_member_id");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
